Sprint #10
PisarevAlexander/java-filmorate pull request #4
Opened 2023-04-30 07:22 UTC by PisarevAlexander

2023-04-30 10:25 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-04-30 10:25 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    @ResponseStatus(HttpStatus.BAD_REQUEST)
Нужно оставить только один класс для BAD_REQUEST.
Перенеси String parameter; в класс BadRequestException и используй только его.

2023-04-30 10:25 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmStorage filmStorage;
Хранилища тут уже быть не должно!
Только сервис.

Мы строим трёх уровневую архитектуру.
Трехуровневая архитектура контроллер-сервис-хранилище - это подход к разделению ответственности и функциональности в разработке программного обеспечения. Он состоит из следующих уровней:

1. Контроллер - это первый уровень архитектуры, который отвечает за входные данные пользователей и контролирует логику обработки запросов. Контроллеры могут получать данные от пользователей и отправлять их на следующий уровень для обработки.

2. Сервис - это второй уровень архитектуры, который отвечает за логику бизнес-процессов и обработку запросов от контроллеров. Здесь находятся методы, которые осуществляют промежуточную обработку данных и подготавливают данные для хранения или передачи. 

3. Хранилище - это последний уровень архитектуры, который отвечает за хранение и управление данными. Он может включать любой тип хранилища данных, такой как базы данных или файловая система. Хранилище обеспечивает методы для операций чтения/записи данных, которые используются на уровне сервиса.

Каждый уровень архитектуры имеет свою собственную функциональную область и логически разделенные зоны ответственности. Это позволяет достигать лучшей модульной структуры приложения, что облегчает его разработку, тестирование и поддержку.

2023-04-30 10:25 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        List<Film> topFilm = filmStorage.getAllFilm().stream()
Переложи работу по поиску 10 лучших именно на хранилище.
Возвращать все фильмы из хранилища не хорошо.

В последующих реализациях, при переходе к базе данных именно она будет это делать.

2023-04-30 10:25 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    Film getFilmById(int filmId);
Давай разделять сервисы и хранилища.
В сервисах используем глагол `get` а в хранилищах `find`.

Кроме этого, в хранилище, предпочтительно в методе findById возвращать Optional, т.е. `Optional<Film> findById(int id)`

2023-04-30 10:25 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    public Film updateFilm(@RequestBody Film film) {
Методы не висят в воздухе!
Поэтому нет нужды в них повторять название сущности, например: `filmService.updateFilm()`

Получается масло-масляное! 

Лучше: `filmService.create()` `userService.update()`

2023-04-30 10:25 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +            throw new NotFoundException("id " + filmId + "не найден");
Из хранилища мы такие исключения не бросаем!
Это работа сервиса...
Вообще никаких исключений, который ты создал из хранилища не кидай, только из сервиса.

2023-04-30 10:25 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +public class InMemoryUserStorage implements UserStorage {
Я комментил все к сервису и хранилищу фильмов, ну а ты, я думаю, понимаешь что все это надо переносить и на сущность user.

2023-05-01 13:55 UTC, FanaticFiz requested changes

2023-05-01 13:55 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw new NotFoundException("Переменная id должна быль больше 0");
Это BadRequestException ! 
Клиент указал некорректный id

2023-05-01 13:55 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Optional<Film> film = filmStorage.findFilmById(id);
Тут всё технически верно, а я лишь покажу тебе как пользоваться тем что у нас Optional

```
    public Film getFilmById(int id) {
        return filmStorage.findFilmById(id)
                          .orElseThrow(() -> new NotFoundException("Not found film by id: " + id));
    }
```

Попробуй теперь и в других местах покрутить код с новыми знаниями, посмотри какие есть еще методы, кроме `orElseThrow`

2023-05-01 13:55 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    List<Film> findAllFilm();
`findAllFilm() -> findAll()`

Не пиши film, это понятно из названия интерфейса.
К тому же призываю тебя действовать консистентно/единообразно.

В методах create/update ты ничего лишнего не приписывал.

2023-05-01 13:55 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Optional<Film> updatedFilm = filmStorage.update(film);
Нет, ты в сервисе проверь перед обновлением что сущность существует, и если ее нет кидаем исключение.

Проверять это в хранилище нельзя/не правильно.

Не возвращай при update Optional.
Можешь вернуть только обновленную сущность или void

2023-05-02 12:25 UTC, PisarevAlexander commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw new NotFoundException("Переменная id должна быль больше 0");
Тесты в постман настроены на 404 ошибку при некорректных id. Тут переделать не смогу.

2023-05-02 18:35 UTC, FanaticFiz approved these changes

2023-05-08 10:07 UTC, merged